# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [10.16.0] # 配置所需node版本
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install yarn # 安装yarn
        run: npm install yarn -g
      - name: Install dependencies # 安装依赖
        run: yarn install
      - name: Build # 打包代码
        run: yarn build
      - name: Install coscmd
        run: sudo pip install coscmd
      - name: Configure coscmd
        env:
          SECRET_ID: ${{secrets.SECRET_ID}}
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          BUCKET: console-1300990907
          REGION: ap-shanghai
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
      - name: Upload
        run: coscmd upload -rs --delete -f ./dist/ /
